# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details#
#
version: 2
general:
  branches:
    only:
      - dev
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: jacekmarchwicki/android:java7-8
      #working_directory: ~/repo
    environment:
      GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: prepare
          command: ./update.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: deploy
          command: ./gradlew tasks --all
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
