# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      #working_directory: ~/repo
      
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
       - sudo ANDROID_HOME=/usr/local/android-sdk-linux
      - checkout
      - run:
          name: Update versions
          command: ./update.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Delivery
          command: ./gradlew clean && ./gradlew assembleRelease -PVERSION_NAME=0.0.1 && ./gradlew publish -PVERSION_NAME=0.0.1
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}