# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details#
#
version: 2
general:
  branches:
    only:
      - dev
machine:
  environment:
    REPO_OS_OVERRIDE: linux
jobs:
  build:
    docker:
      - image: circleci/android:api-$PLATFORM_API-alpha
      #working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            raw_commit_msg="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            export GIT_COMMIT_DESC="$(echo $raw_commit_msg| grep -oP " [0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"
            ./update.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: deploy
          command: ./gradlew assembleDebug
      - run:
          name: checkin
          command: |
            git config --global user.email nikitosgleb@gmail.com
            git config --global user.name "Gleb Nikitenko"
            git fetch && git checkout master && git merge dev
            git tag v$GIT_COMMIT_DESC && git push --follow-tags
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
