# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details#
#
version: 2
general:
  branches:
    only:
      - dev
machine:
  environment:
    REPO_OS_OVERRIDE: linux
jobs:
  build:
    docker:
      - image: circleci/android:api-$PLATFORM_API-alpha
      #working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - add_ssh_keys:
          fingerprints:
              - "15:2c:dd:d9:fd:56:fa:d8:04:bd:45:5d:49:eb:ec:77" # user key
              - "d9:7a:16:d2:66:66:ee:f5:79:43:22:36:7c:72:7c:03" # deploy key
              - "27:83:76:8c:99:57:5c:3c:01:59:be:1c:65:93:62:c4" # ssh permissions
      - checkout
      - run:
          name: prepare
          command: |
            export RAW_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            export GIT_COMMIT_DESC="$(echo $RAW_COMMIT_MSG | grep -oP " [0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"
            git clone git@bitbucket.org:NikGleb/android-builds.git && ./android-builds/prepare.sh $PLATFORM_API
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: deploy
          command: |
            export RAW_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            export GIT_COMMIT_DESC="$(echo $RAW_COMMIT_MSG | grep -oP " [0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"            
            export RELEASE_VERSION="$(echo $GIT_COMMIT_DESC | grep -oP "[0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"
            ./gradlew release && ./gradlew publish
      - run:
          name: checkin
          command: |
            export RAW_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            export GIT_COMMIT_DESC="$(echo $RAW_COMMIT_MSG | grep -oP " [0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"            
            tagVersion=v"$(echo $GIT_COMMIT_DESC | grep -oP "[0-9].[0-9].[0-9].([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])")"
            git config --global user.email nikitosgleb@gmail.com
            git config --global user.name "Gleb Nikitenko"
            git fetch && git checkout master && git merge dev
            git push && git tag $tagVersion && git push origin $tagVersion
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
