//
// Created by AlexS on 23.01.17.
//


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etoolkit_photoeditor_uploader_LoveUploader */
#include <cmath>

#include "lovehash.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32_t gs() {

    uint32_t i = 0;
    uint32_t j = 30000;
    j *= j;

    uint32_t n = 0;
    for (uint32_t o = 0; o <= j; o += (1000 * 1000)) {
        n = o;
    }

    return n - (84514000 + (sqrt(44944)));

}
JNIEXPORT jlong JNICALL
Java_com_etoolkit_photoeditor_uploader_LoveUploader_getShortHash(
        JNIEnv *env,
        jclass type,
        jbyteArray data_,
        jint length) {
    jbyte *data = env->GetByteArrayElements(data_, NULL);

    //const uint32_t seed = 815485788;
    uint32_t hash;
    LoveHash3_x86_32(data, length, gs(), &hash);

    env->ReleaseByteArrayElements(data_, data, 0);
    return (jlong) (unsigned long long) hash;
}

#ifdef __cplusplus
}
#endif