 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_NetworkUtils */

#ifndef _Included_ok_OkAndroidUtils
#define _Included_ok_OkAndroidUtils

    #ifdef __cplusplus
        extern "C" {
    #endif

    /*
     * Class:       network_NetworkUtils
     * Method:      createPipe
     * Signature:   (Ljava/io/FileDescriptor;(Ljava/io/FileDescriptor;)Z
     */
    JNIEXPORT jboolean JNICALL
    Java_network_NetworkUtils_createPipe(JNIEnv *, jclass, jobject, jobject);

    /*
     * Class:       network_NetworkUtils
     * Method:      createPfd
     * Signature:   (Ljava/io/FileDescriptor;)Landroid/os/ParcelFileDescriptor;
     */
     JNIEXPORT jobject JNICALL
     Java_network_NetworkUtils_createPfd(JNIEnv *, jclass, jobject);

    #ifdef __cplusplus
        }
    #endif

#endif 
