/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drawables_BitmapDrawable */

#ifndef _Included_drawables_BitmapDrawable
#define _Included_drawables_BitmapDrawable

    #ifdef __cplusplus
        extern "C" {
    #endif

    /*
     * Class:     drawables_BitmapDrawable
     * Method:    update
     * Signature: (Landroid/graphics/ColorMatrixColorFilter;)Z
     */
    JNIEXPORT jboolean JNICALL
    Java_drawables_BitmapDrawable_update(JNIEnv *, jclass, jobject);
    /*
     * Class:     drawables_BitmapDrawable
     * Method:    getMatrix
     * Signature: (Landroid/graphics/ColorMatrixColorFilter;)Landroid/graphics/ColorMatrix
     */
    JNIEXPORT jobject JNICALL
    Java_drawables_BitmapDrawable_getMatrix(JNIEnv *, jclass, jobject);

    #ifdef __cplusplus
        }
    #endif

#endif